### ISSUE TITLE
Netlify function not working because of missing id

### ISSUE THREAD

**Issue by danielgara** [PacktPublishing/Jumpstart-Jamstack-Development#3]
https://github.com/PacktPublishing/Jumpstart-Jamstack-Development/blob/eb79b33a2e7eb89c931ca71738f61e49e68a6de6/web/src/pages/index.js#L146

Dear Author,

I tried to use this code, but I was not able to get the new events (which were submitted through the index form) in my studio dashboard. I got this error in my netlify functions log:

_2:10:07 PM: 18740345 ERROR  Invoke Error 	{"errorType":"ClientError","errorMessage":"Reference is not a valid document ID_

I found the solution, I replace this line:

```
<option id={venue._id}>{venue.name}</option>
```

With this line:

```
<option id={venue._id} value={venue._id}>{venue.name}</option>
```

**Comment by VincenzoGambino** [comment]
Thank you, @danielgara,
I will test it and I will apply the changes today.

**Comment by VincenzoGambino** [comment]
Hi @danielgara ,

The branch chapter_eleven has been updated.

Cheers
